In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv("Stars.csv")
df

Temperature              L          R    A_M  Color Spectral_Class  Type
0           3068       0.002400     0.1700  16.12    Red              M     0
1           3042       0.000500     0.1542  16.60    Red              M     0
2           2600       0.000300     0.1020  18.70    Red              M     0
3           2800       0.000200     0.1600  16.65    Red              M     0
4           1939       0.000138     0.1030  20.06    Red              M     0
..           ...            ...        ...    ...    ...            ...   ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5
237         8829  537493.000000  1423.0000 -10.73  White              A     5
238         9235  404940.000000  1112.0000 -11.23  White              A     5
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5

[240 rows x 7 columns]

In [2]:
df.shape

(240, 7)

In [3]:
df.isnull().sum()

Temperature       0
L                 0
R                 0
A_M               0
Color             0
Spectral_Class    0
Type              0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature     240 non-null    int64  
 1   L               240 non-null    float64
 2   R               240 non-null    float64
 3   A_M             240 non-null    float64
 4   Color           240 non-null    object 
 5   Spectral_Class  240 non-null    object 
 6   Type            240 non-null    int64  
dtypes: float64(3), int64(2), object(2)
memory usage: 11.3+ KB


In [5]:
df.describe()

Temperature              L            R         A_M        Type
count    240.000000     240.000000   240.000000  240.000000  240.000000
mean   10497.462500  107188.361635   237.157781    4.382396    2.500000
std     9552.425037  179432.244940   517.155763   10.532512    1.711394
min     1939.000000       0.000080     0.008400  -11.920000    0.000000
25%     3344.250000       0.000865     0.102750   -6.232500    1.000000
50%     5776.000000       0.070500     0.762500    8.313000    2.500000
75%    15055.500000  198050.000000    42.750000   13.697500    4.000000
max    40000.000000  849420.000000  1948.500000   20.060000    5.000000

In [6]:
col_names=['Color','Spectral_Class']
for col in col_names:
    print(df[col].value_counts())

Red                   112
Blue                   56
Blue-white             26
Blue White             10
yellow-white            8
White                   7
Blue white              4
white                   3
Yellowish White         3
yellowish               2
Whitish                 2
Orange                  2
White-Yellow            1
Pale yellow orange      1
Yellowish               1
Orange-Red              1
Blue-White              1
Name: Color, dtype: int64
M    111
B     46
O     40
A     19
F     17
K      6
G      1
Name: Spectral_Class, dtype: int64


In [7]:
# convert categorical data into numerical data
from sklearn.preprocessing import OrdinalEncoder
ord_enc = OrdinalEncoder()
df["Color"] = ord_enc.fit_transform(df[["Color"]])
df["Spectral_Class"] = ord_enc.fit_transform(df[["Spectral_Class"]])

In [8]:
Features = df.iloc[:, 0:7].values
Labels = df.iloc[:,-1].values

In [9]:
Features=abs(Features)

In [10]:
from sklearn.feature_selection import SelectKBest, f_classif, chi2

for i in range(1,len(df.columns)-1):
    sele=SelectKBest(chi2,k=i)
    c=sele.fit_transform(Features,Labels)
print(c)

[[3.06800e+03 2.40000e-03 1.70000e-01 1.61200e+01 0.00000e+00]
 [3.04200e+03 5.00000e-04 1.54200e-01 1.66000e+01 0.00000e+00]
 [2.60000e+03 3.00000e-04 1.02000e-01 1.87000e+01 0.00000e+00]
 ...
 [8.82900e+03 5.37493e+05 1.42300e+03 1.07300e+01 5.00000e+00]
 [9.23500e+03 4.04940e+05 1.11200e+03 1.12300e+01 5.00000e+00]
 [3.78820e+04 2.94903e+05 1.78300e+03 7.80000e+00 5.00000e+00]]


In [11]:
sk = SelectKBest(chi2, k=3)
Features_best = sk.fit_transform(Features, Labels)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Features_best, Labels) 

In [13]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()

In [14]:
gb.fit(X_train,Y_train)

GradientBoostingClassifier()

In [15]:
Y_pred=gb.predict(X_test)


In [16]:
from sklearn.metrics import classification_report,accuracy_score

print(accuracy_score(Y_pred,Y_test))
print(classification_report(Y_pred,Y_test))


0.9833333333333333
              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      0.93      0.96        14
           2       1.00      1.00      1.00        12
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         8

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.99        60
weighted avg       0.98      0.98      0.98        60

