In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv("bank.csv")
df

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [2]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.0+ MB


In [4]:
df.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [5]:
df.shape

(11162, 17)

In [6]:
col_names=['job','marital','education','default','housing','loan','contact','month','poutcome','deposit']
for col in col_names:
    print(df[col].value_counts())


management       2566
blue-collar      1944
technician       1823
admin.           1334
services          923
retired           778
self-employed     405
student           360
unemployed        357
entrepreneur      328
housemaid         274
unknown            70
Name: job, dtype: int64
married     6351
single      3518
divorced    1293
Name: marital, dtype: int64
secondary    5476
tertiary     3689
primary      1500
unknown       497
Name: education, dtype: int64
no     10994
yes      168
Name: default, dtype: int64
no     5881
yes    5281
Name: housing, dtype: int64
no     9702
yes    1460
Name: loan, dtype: int64
cellular     8042
unknown      2346
telephone     774
Name: contact, dtype: int64
may    2824
aug    1519
jul    1514
jun    1222
nov     943
apr     923
feb     776
oct     392
jan     344
sep     319
mar     276
dec     110
Name: month, dtype: int64
unknown    8326
failure    1228
success    1071
other       537
Name: poutcome, dtype: int64
no     5873
yes    5289
Name: d

In [7]:
# Converting negative values into positive by using  
df['pdays']=abs(df['pdays'])

In [8]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1      1         0  unknown     yes  
1    5   may      1467         1      1         0  unknown     yes  
2    5   may      1389         1      1         0  unknown     yes  
3    5   may       579         1      1         0  unknown     yes  
4    5   may       673         2      1         0  unknown     yes

In [9]:
from sklearn.preprocessing import OrdinalEncoder
ord_enc = OrdinalEncoder()
df["job"] = ord_enc.fit_transform(df[["job"]])
df["marital"] = ord_enc.fit_transform(df[["marital"]])
df["education"] = ord_enc.fit_transform(df[["education"]])
df["default"] = ord_enc.fit_transform(df[["default"]])
df["housing"] = ord_enc.fit_transform(df[["housing"]])
df["loan"] = ord_enc.fit_transform(df[["loan"]])
df["contact"] = ord_enc.fit_transform(df[["contact"]])
df["month"] = ord_enc.fit_transform(df[["month"]])
df["poutcome"] = ord_enc.fit_transform(df[["poutcome"]])
df["deposit"] = ord_enc.fit_transform(df[["deposit"]])


In [10]:
Features = df.iloc[:, :-1].values
Labels = df.iloc[:,-1].values

In [11]:
Features=abs(Features)

In [12]:
Features.shape

(11162, 16)

In [13]:
Labels=abs(Labels)

In [14]:
from sklearn.feature_selection import SelectKBest, f_classif, chi2

for i in range(1,len(df.columns)-1):
    sele=SelectKBest(chi2,k=i)
    c=sele.fit_transform(Features,Labels)
print(c)

[[ 59.   0.   1. ...   1.   0.   3.]
 [ 56.   0.   1. ...   1.   0.   3.]
 [ 41.   9.   1. ...   1.   0.   3.]
 ...
 [ 32.   9.   1. ...   1.   0.   3.]
 [ 43.   9.   1. ... 172.   5.   0.]
 [ 34.   9.   1. ...   1.   0.   3.]]


In [15]:
sk = SelectKBest(chi2, k=7)
Features_best = sk.fit_transform(Features, Labels)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Features_best, Labels) 

In [17]:
from sklearn.svm import LinearSVC
ls=LinearSVC()

In [18]:
ls.fit(X_train,Y_train)

LinearSVC()

In [19]:
Y_pred=ls.predict(X_test)


In [20]:
from sklearn.metrics import classification_report,accuracy_score

print(accuracy_score(Y_pred,Y_test))
print(classification_report(Y_pred,Y_test))


0.7190970978144035
              precision    recall  f1-score   support

         0.0       0.78      0.72      0.75      1609
         1.0       0.65      0.72      0.68      1182

    accuracy                           0.72      2791
   macro avg       0.72      0.72      0.72      2791
weighted avg       0.72      0.72      0.72      2791

